[book]
title = "Computer Science @ Sapienza"
authors = ["Ionut Cicio"]
description = "Just code & projects for university"
language = "en"
src = "book"

# [rust]
# edition = "2018"

[build]
build-dir = "docs"
create-missing = false

[preprocessor.index]

[preprocessor.links]


[output.html]
mathjax-support = true
site-url = "/university/"
git-repository-url = "https://github.com/CuriousCI/university"
# additional-css = ["custom.css"]

[output.html.playground]
editable = false 
line-numbers = true

# [output.html.search]
# limit-results = 15

